### ISSUE TITLE
How to properly call a function (params) with LLVM-Node.

### ISSUE THREAD

**Issue by aiko-is-bored** [MichaReiser/llvm-node#114]
I've looked through the tests and I've not found anything that details how to call a function with parameters in LLVM-Node. Do I just use an array? Is it not possible?

**Comment by vihanb** [comment]
The API mimics the original LLVM one. Use IRBuilder#createCall

**Comment by aiko-is-bored** [comment]
> The API mimics the original LLVM one. Use IRBuilder#createCall

All right.
