### ISSUE TITLE
Current cmake-js version uses vulnerable dependencies (lodash), requires update

### ISSUE THREAD

**Issue by diegoperini** [MichaReiser/llvm-node#57]
| Result of | `npm audit` |
| - | - |
| Low | Prototype Pollution |
| Package | lodash |
| Patched in | >=4.17.5 |
| Dependency of | llvm-node |
| Path | llvm-node > cmake-js > lodash |
| More info | https://nodesecurity.io/advisories/577 |

**Comment by MichaReiser** [comment]
Fixed with #58
