### ISSUE TITLE
No way to do builder.createStore() for float or half constants

### ISSUE THREAD

**Issue by diegoperini** [MichaReiser/llvm-node#67]
In order to be able to work with non double floating point constants, we need the mappings for `APFloat` and `ConstantFP::get(Type* Ty, const APFloat &V)` APIs.

http://llvm.org/doxygen/classllvm_1_1APFloat.html
http://llvm.org/doxygen/classllvm_1_1ConstantFP.html#ac698873f7b353f3a37cb8577b74acf72

**Comment by diegoperini** [comment]
I will look into it once the contributions guidelines are up.

**Comment by ovr** [comment]
@MichaReiser Can you assign this issue to me? I will start to work on it on weekends, Thanks!
