### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by cloudrex** [MichaReiser/llvm-node#78]
Installation fails on Ubuntu 18.04 when CMake begins linking process. Any ideas? This is extremely frustrating.

![image](https://user-images.githubusercontent.com/41349879/53540732-b8ddaa00-3ae4-11e9-92f5-c46f07ddff44.png)

**Comment by vihanb** [comment]
Do you have zlib installed? Though it looks like ld is interpreting `-lz` as a file... which is weird

**Comment by cloudrex** [comment]
Everything works fine after installing `zlib`. Thanks!
