### ISSUE TITLE
StoreInst type problem (ConstantFP)

### ISSUE THREAD

**Issue by cloudrex** [MichaReiser/llvm-node#80]
I'm trying to create a store instruction that will store a float on a float allocation (logical).

However, I'm running into the problem that when I access `ConstantFP.get()`, I have no way of specifying the type I want for the value. So `ConstantFP.get()` accepts `LLVMContext` and a number in that order.

But in the LLVM documentation this is possible:

![image](https://user-images.githubusercontent.com/41349879/55687633-3941c700-593d-11e9-81fc-66c4eb126eb8.png)

Has this method not been implemented? The other way I tried was changing the `type` property of the returned value manually, but it shouldn't be like this... (have not verified working).

This is what is generated from my current code:

```llvm
define void @main() {
  %pi = alloca float
  store double 3.140000e+00, float* %pi
  ret void
}
```

from:

```ts
...
const myFloat = parseFloat( ... )
ConstantFP.get(<context>, myFloat); // I want a float, creates a double instead.
...
```

The ConstantInt class' `get()` method looks more flexible, as it allows to specify the size, etc.

**Comment by MichaReiser** [comment]
@cloudrex You're right. This wasn't yet supported. I only implemented the APIs that I needed once I worked with LLVM. The majority of LLVM is still not covered.

I created a PR adding support for constantFP #81
