### ISSUE TITLE
Build issues with Node v12

### ISSUE THREAD

**Issue by vihanb** [MichaReiser/llvm-node#84]
Not sure what is causing this but looks like there are some build issues arising when building for node v12 as have cropped up in CI:

```
error: no matching function for call to ‘v8::Value::ToString()’
     llvm::DataLayout layout { ToString(info[0]->ToString()) };
                                                          ^
note: candidates are:
In file included from ...

layout.cc:5:
v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
note:   candidate expects 1 argument, 0 provided
```

This only started happening with node v12 so I am guessing v8 api changed? Few other v12 errors I am also seeing in v12 also probably related to API changes: https://travis-ci.org/vsl-lang/VSL/jobs/525749327#L502

**Comment by MichaReiser** [comment]
Hi @vihanb 

This most certainly because of a native API change with node 12 and can probably be fixed with upgrading the dependency to napi.

**Comment by MichaReiser** [comment]
This is fixed in the latest version in master
