### ISSUE TITLE
Can't found LLVM API: GetElementPtrInst

### ISSUE THREAD

**Issue by mohanson** [MichaReiser/llvm-node#92]
I want declare a number array and give it a value. 

I can do this with clang, and the corresponding IR is

```
int a[3];
a[0] = 1;
```

```
%1 = alloca i32, align 4
%2 = alloca [3 x i32], align 4
store i32 0, i32* %1, align 4
%3 = getelementptr inbounds [3 x i32], [3 x i32]* %2, i64 0, i64 0
store i32 1, i32* %3, align 4
```

But  don't know how to implement it in llvm-node , because I cant' found `getelementptr ` api in llvm-node

**Comment by vihanb** [comment]
You can use the IRBuilder's `createInBoundsGEP`:

https://github.com/MichaReiser/llvm-node/blob/bc90d33a97c750447697a1330f3fe6517942ea16/llvm-node.d.ts#L591

**Comment by mohanson** [comment]
Thanks, I understand how to implement an array.
