### ISSUE TITLE
Doubts about the `ConstantExpr` object

### ISSUE THREAD

**Issue by mohanson** [MichaReiser/llvm-node#93]
Hi, MichaReiser!

I want create a **global** string, and I can do this right now by such codes

```ts
const v = llvm.ConstantDataArray.getString(context, "Hello");
const r = new llvm.GlobalVariable(module, v.type, false, llvm.LinkageTypes.ExternalLinkage, v, name);
```

But I got some question, The generated IR is

```
@s = global [6 x i8] c"Hello\00"
```

See, the `@s` is an array.

When I declare a global string in `clang`, The generated IR is

```
@.str = private unnamed_addr constant [6 x i8] c"world\00", align 1
@s = global i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i32 0, i32 0), align 8
```

the `@s` is an `i8*`

I think clang has done one more thing by

```
ConstantExpr::getBitCast(v, i8->getPointerTo())
```

I want my global string's type is `i8*` so I can pass in to system's function `stdio::printf` as an argument. But I don't known how can I do it because I can't find the `ConstantExpr` in llvm-node.

**Comment by mohanson** [comment]
I know where I am wrong, The right codes are

```ts
const v = llvm.ConstantDataArray.getString(context, node.text);
const r = new llvm.GlobalVariable(module, v.type, false, llvm.LinkageTypes.ExternalLinkage, v, name);
const a = builder.createBitCast(r, llvm.Type.getInt8Ty(context).getPointerTo() );
const b = new llvm.GlobalVariable(module, a.type, false, llvm.LinkageTypes.ExternalLinkage, a as llvm.Constant, name);
```

Thanks for your good job, llvm-node is awesome.

**Comment by vihanb** [comment]
I recommend using the `IRBuilder.createGlobalString[Pointer]` functions:

https://github.com/MichaReiser/llvm-node/blob/master/llvm-node.d.ts#L587-L589

which encapsulate this functionality

**Comment by mohanson** [comment]
@vihanb

```ts
const context = new llvm.LLVMContext()
const builder = new llvm.IRBuilder(context)

builder.createGlobalStringPtr("Hello");
```

This codes cause `Segmentation fault (core dumped)`
